### PR TITLE
Adapt Python3.5 native async syntax

### PR DESCRIPTION
**Pull request by miili**
Thanks for this library!
Just syntactic sugar, gets rid of 10 lines... imo this syntax is more crisp.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Hi Miili,
I would like to merge this. Unfortunately, I still need Python 3.4/3.5 compatibility for the Mission Pinball Framework. A lot of our users just cannot upgrade yet (mostly build and dependency reasons on Mac and Windows). We hope to change that in the future (probably a year or two). I would like to keep this PR open and merge it once this is resolved.

Jan

**Comment by miili** [comment]
I was mistaken, the `async` / `await` syntax was introduced in 3.5.
https://docs.python.org/3/library/asyncio-task.html#coroutines

**Comment by jabdoa2** [comment]
Yeah I think we can/should cut 3.4 at some point. Probably after Ubuntu 14.04 when EOL which will be April 2019.

**Comment by jabdoa2** [comment]
Fixed by #7

**Pull request closed without merging**
